import { NextPageWithLayout } from './_app';
import SEOHead from '../components/SEOHead';
import Image from "next/legacy/image";
import styles from './index.module.scss';
import { useDispatch, useSelector } from 'react-redux';
import { RootState } from '../store/store';
import { useAppSelector, useInterval, useAppDispatch } from '../hooks';
import { selectLoading, setLoading } from '../store/example';
import { useGetPokemonByNameQuery } from '../services/pokemon';
import Layout from '../layouts/default';
import { useStyles } from '@/hooks/useStyles';
const Home: NextPageWithLayout = () => {
  const { data, error, isLoading } = useGetPokemonByNameQuery('staryu');
  const s = useStyles(styles);
  const loading = useAppSelector(selectLoading);
  const dispatch = useAppDispatch();

  return (
    <div className={styles.container}>
      
      <SEOHead>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </SEOHead>

      <main className={s('main')}>
        <h1 className={s('title')}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>

        <h2 className={'title'}>
          {String(isLoading)} {data?.name ?? 'No pokemon'}
        </h2>

        <p className={s('description')}>
          Get started by editing{' '}
          <code className={s('code')}>pages/index.tsx</code>
        </p>

        <div className={s('grid')}>
          <a href="https://nextjs.org/docs" className={s('card')}>
            <h2>Documentation &rarr;</h2>
            <p>Find in-depth information about Next.js features and API.</p>
          </a>

          <a href="https://nextjs.org/learn" className={s('card')}>
            <h2>Learn &rarr;</h2>
            <p>Learn about Next.js in an interactive course with quizzes!</p>
          </a>

          <a
            href="https://github.com/vercel/next.js/tree/canary/examples"
            className={s('card')}
          >
            <h2>Examples &rarr;</h2>
            <p>Discover and deploy boilerplate example Next.js projects.</p>
          </a>

          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={s('card')}
          >
            <h2>Deploy &rarr;</h2>
            <p>
              Instantly deploy your Next.js site to a public URL with Vercel.
            </p>
          </a>
        </div>
      </main>

      <footer className={s('footer')}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={s('logo')}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
};

// layouts are added like this via the getLayout function, the Layout is returned
// this structure allows for react to be aware of state and properly perform state updates
Home.getLayout = function getLayout(page) {
  return (
    <Layout>
      {page}
    </Layout>
  );
};

export default Home;


